trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Gitleaks@2
  inputs:
    scanlocation: '$(Build.SourcesDirectory)'
    configtype: 'default'
    scanmode: 'all'
    reportformat: 'sarif'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'azuresonar'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=Azuredemo
- task: SonarQubePublish@5
  inputs:
    pollingTimeoutSec: '300'
            
- task: Docker@2
  inputs:
    containerRegistry: 'docker push mani7444/azure:tagname'
    repository: 'mani7444 / azure'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- script: |
    sudo apt-get install wget apt-transport-https gnupg lsb-release
    wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
    echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
    sudo apt-get update
    sudo apt-get install trivy

  displayName: 'Download and install Trivy'
- task: CmdLine@2
  displayName: "Run trivy scan"
  inputs:
    script: |
      trivy image mani7444/spring-boot-mongo